//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pp11
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class База_данныхEntities1 : DbContext
    {
        public База_данныхEntities1()
            : base("name=База_данныхEntities1")
        {
        }

        private static База_данныхEntities1 _context;
        public static База_данныхEntities1 GetContext()
        {
            if (_context == null)
                _context = new База_данныхEntities1();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categ> categ { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<prodact> prodact { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
